### ISSUE TITLE
Support for Keyword Overview (All Databases) aka phrase_all ?

### ISSUE THREAD

**Issue by gchiaren** [arambert/semrush#13]
Can't seem to figure out how I would run a keyword overview against _all_ regional databases. In the API, it's the [phrase_all](http://www.semrush.com/api-documentation/?1419367196#phrase_all) call. 

I tried passing in both an array and a comma delimited string of multiple regional databases to the db property, but it didn't work. 

In other words, if I wanted to get search volumes for all regional databases, is there a way to get them all in a single call? Or do I have to make a call for all the individual databases ("us", "uk", "ca", "ru", etc.) and add them all up? Seems like that would eat up my credits fairly quickly.

Thanks!

**Comment by arambert** [comment]
This issue has been inactive for more than 2 years. I'm closing it.
