### ISSUE TITLE
Semrush::Report.remaining_quota never updates on api_key changes

### ISSUE THREAD

**Issue by sadeden** [arambert/semrush#7]
If I do this :
Semrush.api_key = 'api key1'
puts Semrush::Report.remaining_quota
Semrush.api_key = 'api key 2'
puts Semrush::Report.remaining_quota

The last call use the same @remaining_quota_url with wrong api key.
If this behaviour is not wanted, I would suggest that @remaining_quota_url is niled on api_key updates

**Comment by arambert** [comment]
This issue has been inactive for more than 2 years. I'm closing it.
